cStone/cStone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cStone/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'main'

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="home.html"),
        name="home",
    ),
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name="about_us",
    ),
    path(
        "new-quote/",
        TemplateView.as_view(template_name="new_quote.html"),
        name="new_quote",
    ),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us",
    ),
]

cStone/customers/models.py
from django.db import models


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    active = models.BooleanField(default=False)
    osek_num = models.CharField(max_length=50)
    email = models.EmailField()
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

cStone/main/models.py
from django.db import models


class Stone(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=40, default='', unique=True)
    description = models.TextField()

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Category(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=40, default='', unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Processing(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=40, default='', unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    stone = models.ForeignKey(Stone, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(default='', max_length=100)
    slug = models.SlugField(max_length=48, unique=True)
    length = models.DecimalField(verbose_name='Length[CM]', max_digits=4, decimal_places=1)
    width = models.DecimalField(verbose_name='Width[CM]', max_digits=4, decimal_places=1)
    thickness = models.DecimalField(verbose_name='Thickness[MM]', max_digits=3, decimal_places=1)
    stock_units = models.PositiveIntegerField(default=0)
    ordered = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=False)
    processing = models.ForeignKey(Processing, related_name='products', on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Price[NIS]', max_digits=6, decimal_places=1)
    image = models.ImageField(upload_to='products', null=True, blank=True,
                              default='logo-icon.png')
    description = models.TextField(default='')

    @property
    def total_space_m(self):
        return (self.length * self.width)/100

    def __str__(self):
        return self.name

cStone/orders/models.py
from decimal import Decimal

from django.db import models
from main.models import Product
from customers.models import Customer


class Order(models.Model):
    STATUS_CHOICES = [
        ('paid', 'שולם'),
        ('open', 'פתוח'),
        ('rfs', 'מוכן למשלוח'),
        ('canceled', 'מבוטל'),
        ('quote', 'הצעת מחיר')
    ]

    customer = models.ForeignKey(Customer, related_name='orders',
                                 on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=8,
        choices=STATUS_CHOICES,
        default='open',
    )

    discount_percentage = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    @property
    def total_cost(self):

        calculation = (
                sum(
                    item.item_cost for item in self.items.all()
                ) *
                (1-(Decimal(self.discount_percentage/100)))
        )

        return round(calculation, 2)


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)

    quantity = models.PositiveIntegerField(default=1)
    discount_percentage = models.PositiveIntegerField(default=0)

    def __str__(self):
        return 'Order {} Item {}'.format(self.order.id, self.id)

    @property
    def item_cost(self):
        calculation = (
                self.product.price *
                (1-(Decimal(self.discount_percentage/100))) *
                self.quantity
        )

        return round(calculation, 2)

cStone/main/forms.py
from django import forms
from django.core.mail import send_mail
import logging

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label="Your name", max_length=100)
    message = forms.CharField(
        max_length=600, widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "aymans.eng@gmail.com",
            ["ayman-said@live.com"],
            fail_silently=False,
        )

cStone/customers/views.py
from django.shortcuts import render

# Create your views here.

cStone/main/views.py
from django.views.generic.edit import (
    FormView,
)
from . import forms


class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

cStone/orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from orders.models import Order, OrderItem

# Create your views here.


def new_quote(request):
    new_order = Order.objects.create(status='quote')

    # return render(request, r,
    #               {'form': form, 'course': course})

cStone/main/templates/about_us.html
{% extends "base.html" %}

{% block content %}
  <h2>About us</h2>
  <p>CStone is a company that sells beautiful stones online.</p>
{% endblock content %}

cStone/main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--Required meta tags -->
    <meta charset="utf-8">
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap 4.3.1 CSS -->
    <link
      rel="stylesheet"
      href="{% static "css/bootstrap.min.css" %}">
    <title>CStone 2019</title>
  </head>
  <body style="direction: rtl" class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">CStone</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse"
        id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li
            {% url 'main:new_quote' as new_quote_url %}
            class="nav-item {% if request.path == new_quote_url %}active{% endif %}">
            <a class="nav-link" href="{{new_quote_url}}">הצעת מחיר</a>
          </li>
          <li
            class="nav-item {% if request.path == "/about-us/" %}active{% endif %}">
            <a class="nav-link" href="/about-us/">About us</a>
          </li>
          <li
            class="nav-item {% if request.path == "/contact-us/" %}active{% endif %}">
            <a class="nav-link" href="/contact-us/">Contact us</a>
          </li>
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

cStone/main/templates/contact_form.html
{% extends "base.html" %}
{% block content %}
  <h2>Contact us</h2>
  <p>Please fill the form below to contact us</p>
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock content %}

cStone/main/templates/home.html
{% extends "base.html" %}

{% block content %}
  <h2>Home</h2>
  <p>this will be the content of home</p>
{% endblock content %}